# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-28 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_level', models.IntegerField(default=0)),
                ('v_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ModelRelation.User')),
            ],
        ),
    ]
