# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-28 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='v_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ModelRelation.User'),
        ),
    ]
