# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-28 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelation', '0002_auto_20190528_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='v_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ModelRelation.User'),
        ),
    ]
