# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-28 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelation', '0003_auto_20190528_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_addr', models.CharField(max_length=128)),
                ('a_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelRelation.User')),
            ],
        ),
    ]
