# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-28 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelation', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=32)),
                ('g_users', models.ManyToManyField(to='ModelRelation.User')),
            ],
        ),
    ]
