# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-27 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_name', models.CharField(max_length=32, unique=True)),
                ('g_price', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'gaming',
                'ordering': ('g_price',),
            },
        ),
    ]
