# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-27 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('g_price', '-g_id')},
        ),
    ]
