# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-27 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190527_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Praise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_content', models.CharField(max_length=64)),
                ('p_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Book')),
            ],
        ),
    ]
