# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-27 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_praise'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='b_publish_date',
            field=models.DateField(auto_now=True),
        ),
    ]
