# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-27 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_grade_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='g_boy_nums',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='grade',
            name='g_girl_nums',
            field=models.IntegerField(default=70),
        ),
    ]
