version: '3'

networks:
    backend:

services:
    server:
        build: ..
        container_name: tmp-server
        command: php -S 0.0.0.0:80 -t www
        # command: tail -f /dev/null
        working_dir: /var/work
        tty: true
        ports:
            - "6080:80"
        volumes:
            - ../dss_crm:/var/work/
            - ./php.ini:/usr/local/etc/php/php.ini
        # environment:
            # XDEBUG_CONFIG: remote_host=host.docker.internal remote_autostart=On idekey=PHPSTORM remote_port=9000
        networks:
            - backend
        depends_on:
            # - mysql
            - redis

    # mysql:
    #     container_name: tmp-mysql
    #     image: mysql:8.0
    #     networks:
    #         - backend
    #     ports:
    #         - 13306:3306
    #     volumes:
    #         - "./mysql/conf.d/:/etc/mysql/conf.d/"
    #         - "./mysql/my.cnf:/etc/mysql/my.cnf"
    #         - "./mysql/mysql.conf.d/:/etc/mysql/mysql.conf.d/"
    #         - "./mysql/log/:/var/log/mysql/"
    #         - "./mysql/data/:/var/lib/mysql/"
    #         # - "./mysql/run/:/var/run/"
    #         - "./mysql/mysql-files/:/var/lib/mysql-files/"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "123456"
    #         TZ: Asia/Shanghai
    #         MYSQL_USER: test   #创建test用户
    #         MYSQL_PASSWORD: test  #设置test用户的密码w

    redis:
        container_name: tmp-redis
        image: redis:alpine
        networks:
            - backend
        ports:
            - 16379:6379
