# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-05 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='a_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.User'),
            preserve_default=False,
        ),
    ]
