# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-05 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_animal_a_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
