# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-24 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_logo', models.CharField(max_length=32)),
                ('c_price', models.FloatField(default=1)),
                ('c_type', models.CharField(max_length=16)),
            ],
        ),
    ]
