# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-02 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_book_b_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='b_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='b_name',
            field=models.CharField(max_length=32, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='b_price',
            field=models.FloatField(default=1000, verbose_name='价钱'),
        ),
    ]
