# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20190602_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='g_name',
            field=models.CharField(max_length=16, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(max_length=32, verbose_name='学生姓名'),
        ),
    ]
