"""empty message

Revision ID: 4a9521650318
Revises: 23566b6725c4
Create Date: 2019-05-23 10:37:34.766045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a9521650318'
down_revision = '23566b6725c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=256), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
