"""empty message

Revision ID: 6213ac260b85
Revises: 4a9521650318
Create Date: 2019-05-23 16:02:50.177047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6213ac260b85'
down_revision = '4a9521650318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.Column('b_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['b_owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
