# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-28 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190528_0218'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='goods',
            managers=[
            ],
        ),
    ]
